trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: az login --service-principal -u $(AZURE_SP_APPID) -p $(AZURE_SP_PASSWORD) --tenant $(AZURE_TENANT_ID)
  displayName: 'Azure Login'

- script: |
    az group create --name rg-devops-fundamentals-01 --location brazilsouth --tags Environment=Production Project=DevOps-Fundamentals
  displayName: 'Create Resource Group'

- script: |
    for i in {1..50}
    do
      vm_name="DevOps-VM$i"
      az vm create --resource-group rg-devops-fundamentals-01 --name $vm_name --image UbuntuLTS --admin-username devops-user --admin-password $(AZURE_VM_PASSWORD) --size Standard_DS2_v2
    done
  displayName: 'Create Azure Virtual Desktops'

- script: |
    az vmss create --resource-group rg-devops-fundamentals-01 --name DevOpsVMSS --image UbuntuLTS --admin-username devops-user --admin-password $(AZURE_VM_PASSWORD) --instance-count 5 --vm-sku Standard_DS2_v2 --upgrade-policy-mode Automatic
  displayName: 'Create Virtual Machine Scale Set'

- script: |
    az network vnet create --resource-group rg-devops-fundamentals-01 --name DevOpsVNet --address-prefix 10.0.0.0/16
    az network vnet subnet create --resource-group rg-devops-fundamentals-01 --vnet-name DevOpsVNet --name MySubnet --address-prefix 10.0.1.0/24
  displayName: 'Create Network Resources'

- script: |
    az sql server create --resource-group rg-devops-fundamentals-01 --name DevOpsSqlServer --location brazilsouth --admin-user devops-db-user --admin-password $(AZURE_VM_PASSWORD)
    az sql server firewall-rule create --resource-group rg-devops-fundamentals-01 --server DevOpsSqlServer --name AllowAllAzureIPs --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0
    az sql db create --resource-group rg-devops-fundamentals-01 --server DevOpsSqlServer --name MyDB --edition GeneralPurpose --family Gen4 --capacity 2 --collation SQL_Latin1_General_CP1_CI_AS
  displayName: 'Create SQL Database'

  - script: |
    az storage account create --name st-devops-fundamentals --resource-group rg-devops-fundamentals-01 --location brazilsouth --sku Standard_LRS
  displayName: 'Create Storage Account'

- script: |
    az storage container create --name devops --account-name st-devops-fundamentals
  displayName: 'Create Storage Container'

- script: |
    git clone https://github.com/seu-usuario/seu-repositorio.git
    az storage blob upload-batch --destination devops --type block --account-name st-devops-fundamentals --source ./DevOps-Fundamentals-DIO.me
/website
  displayName: 'Upload Folder to Static Website'

- script: |
    az storage blob service-properties update --account-name st-devops-fundamentals --static-website --404-document index.html --index-document index.html
  displayName: 'Configure Static Website'

- script: az logout
  displayName: 'Azure Logout'
